### ISSUE TITLE
Ustalenie funkcjonalności projektu

### ISSUE THREAD

**Issue by Tomasz-Zdeb** [Tomasz-Zdeb/Embedded-Systems-Class-Project#1]
Abyśmy mogli przejść do dalszego etapu realizacji projektu, w którym każdy będzie pracował nad wybranym przez siebie elementem systemu musimy ustalić jakie funkcjonalności będzie posiadał nasz **Rejestrator temperatury**.

Musimy mieć na uwadze ograniczoną liczbę wejść i wyjść w mikroprocesorach z rodziny **STM32**, w związku z czym nie przesadzajmy z ilością funkcjonalności takiego urządzenia. Proponuję aby zawrzeć umiarkowaną ilość funkcjonalności i po prostu zrobić porządnie projekt od początku do końca.

W mojej opinii, must have to:

* pomiar temperatury np. przy pomocy termopary
* monitoring wartości temperatury w czasie rzeczywistym przy pomocy wyświetlacza alfanumerycznego LCD
* przechowywanie szeregu czasowego wartości temperatur w pamięci trwałej
* zapewnienie interfejsu do komunikacji z innymi urządzeniami, np. Ethernet

---

### Proszę o zgłaszanie propozycji funkcjonalności w tym **issue**

---

Na podstawie poczynionych ustaleń utworzę kolejno **issues** dotyczące każdej funkcjonalności/zadania do wykonania umożliwiając każdemu członkowi zespołu przypisanie sobie danego **issue** i pracę nad konkretnym elementem projektu.

**Comment by jackpie2** [comment]
Co do interfejsu komunikacji z innymi urządzeniami, to potencjalną alternatywą dla Ethernetu może być też jakiś moduł WIFI/Bluetooth, jeśli celujemy w coś bardziej typu urządzenia IoT, bo to z reguły tam jest standardem. Oczywiście o ile nie skomplikuje to znacząco projektu

**Comment by Tomasz-Zdeb** [comment]
Warto byłoby dodać LED sygnalizujący obecność zasilania - np. w kolorze czerwonym.

**Comment by Tomasz-Zdeb** [comment]
Musimy zdecydować, który interfejs zaimplementujemy w urządzeniu. Proszę o wypowiedzi w kontekście interfejsu, kto jest za skorzystaniem z jakiego interfejsu (uzasadnienia mile widziane 😀):
* **Bluetooth**
* **Wi/Fi**
* **Ethernet**

**Comment by michalwarchol** [comment]
Według mnie fajnie byłoby żeby to działało przez bluetooth, a telefonie apka pokazująca temperaturę zczytaną z urządzenie przez ten interfejs :D

**Comment by BlessedSamhain** [comment]
Generalnie opcja Bluetooth mi się podoba.

**Comment by Tomasz-Zdeb** [comment]
@PWWP @michalwarchol @bdttd000 @jackpie2 @D4RK0N3dev @BlessedSamhain @S1mon1

Proszę o oddanie głosu w temacie interfejsu który wybieramy do komunikacji ⬆⬆⬆

**Comment by Tomasz-Zdeb** [comment]
@PWWP @michalwarchol @bdttd000 @jackpie2 @D4RK0N3dev @BlessedSamhain @S1mon1

Proszę o przedstawienie ewentualnych nowych funkcjonalności, albo wyrażenie opinii, że to co mamy jest już ok.

---

Z mojej strony to co już mamy wydaje się okej, nie ma co przeprowadzać jakiegoś overengineeringu dla prostego urządzenia

**Comment by D4RK0N3dev** [comment]
> @PWWP @michalwarchol @bdttd000 @jackpie2 @D4RK0N3dev @BlessedSamhain @S1mon1
> 
> Proszę o oddanie głosu w temacie interfejsu który wybieramy do komunikacji ⬆⬆⬆

Jestem za bluetoothem 😉

**Comment by jackpie2** [comment]
Jestem za bluetooth i zgadzam się z tym, że mamy już wystarczająco.
