### ISSUE TITLE
Research i wybór komponentu do przechowywania danych

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Embedded-Systems-Class-Project#10]
Zresearchowanie i wybranie komponentu, odpowiedzialnego za przechowywanie danych (zarejestrowanych temperatur), z kategorii must have, wspomnianej w #1.

**Comment by Tomasz-Zdeb** [comment]
Sugeruję skorzystanie z [niniejszego komponentu](https://botland.com.pl/akcesoria-do-kart-pamieci/1507-modul-czytnika-kart-sd-5903351241342.html?cd=18298825138&ad=&kd=&gclid=Cj0KCQjwteOaBhDuARIsADBqRegNDC0gU8OaF74viSzMJ3p76UiOVGFzNIlWG-sD3G3vK7BwkL9zj84aAuRGEALw_wcB)

**Comment by Tomasz-Zdeb** [comment]
W trakcie laboratoriów, dowiedziałem się, że prawdopodobnie dostęp do karty SD można przeprowadzić w STM32 bezpośrednio bez użycia dodatkowych komponentów.

## Materiały

Zamieszczam materiały, które mogą zawierać potencjalne wskazówki jak dokonać odpowiedniej konfiguracji.

<https://01001000.xyz/2020-08-09-Tutorial-STM32CubeIDE-SD-card/>
<https://www.youtube.com/watch?v=fRfRwMyNE7A&ab_channel=self-studyelectronicengineer>

**Comment by BlessedSamhain** [comment]
Proponuję zastosowanie karty pamięci https://botland.com.pl/karty-pamieci-microsd-sd/2123-karta-pamieci-goodram-m1aa-microsd-16gb-100mbs-uhs-i-klasa-10-z-adapterem-5908267930137.html wraz z gniazdem https://botland.com.pl/akcesoria-do-kart-pamieci/1113-gniazdo-do-karty-pamieci-sd-z-wyrzutnikiem-sd238-5904422349318.html?cd=18298825651&ad=&kd=&gclid=Cj0KCQiAsoycBhC6ARIsAPPbeLvG3jElt5DT_aPbheWtQxQhfNj_gX6wAXOEXh-q6h4_fkQzadwh4NoaAkq5EALw_wcB&fbclid=IwAR3IrRJ_I2taI-QiAh5_7qkvvRFLgxOQCGpf50T6Sg06ZrzVFag3SKZhBoQ . To powinno wspierać SDIO, o którym pisał wcześniej Tomek

**Comment by Tomasz-Zdeb** [comment]
Ok, ciekawy wybór. Dobra robota 👍

**Comment by BlessedSamhain** [comment]
Link do wyżej wskazanej karty wygasł, w związku z czym przedstawiam nową propozycję karty **micro SD** o pojemności 64 GB, obsługującej też tryb **SPI** (co prawdopodobnie nie będzie używane ze względu na wbudowaną w mikroprocesor funkcjonalność **SDIO**), dostępną na stanie magazynowym dostawcy **Mouser Electronics**:

https://www.mouser.pl/ProductDetail/Swissbit/SFSD016GN1AM1MT-I-5E-21P-STD?qs=MyNHzdoqoQLYIxymBNcKzg%3D%3D&fbclid=IwAR0TWalk0Lm6CVDW19KycYiYpYEx4_8X5jO3p9MiM1K0YF11nt575rNrgGs

**Comment by BlessedSamhain** [comment]
Ponieważ tamta karta jest dość droga, to można by w zamian wziąć tę:

https://www.mouser.pl/ProductDetail/SanDisk/SDSDAF3-008G-I?qs=1mbolxNpo8fZAfuISob5lQ%3D%3D&fbclid=IwAR3uOF-8bRSwpAjd_N-QHTMrXoeQ3epMvccDN1hPOX3yTVwqzyb5hUU9yYw
