### ISSUE TITLE
Wyjaśnić kwestie zasięgu członków projektu

### ISSUE THREAD

**Issue by Tomasz-Zdeb** [Tomasz-Zdeb/Embedded-Systems-Class-Project#12]
Warto byłoby wyjaśnić czy projekt realizujemy w ramach danej grupy laboratoryjnej czy w szerszym gronie.

**Comment by BlessedSamhain** [comment]
No chyba miało być tak, że wszyscy w grupie laboratoryjnej tworzą jedną grupę projektową.

**Comment by Tomasz-Zdeb** [comment]
Potwierdziłem tą kwestie na spotkaniu - skład grupy projektowej to skład grupy laboratoryjnej 👍
