### ISSUE TITLE
Research i wybór komponentu do generowania sygnałów dźwiękowych po osiągnięciu zadanej temperatury

### ISSUE THREAD

**Issue by michalwarchol** [Tomasz-Zdeb/Embedded-Systems-Class-Project#13]
Na przykład sygnały ostrzegawcze gdy temperatura spadnie poniżej zera, lub gdy wzrośnie powyżej 30 stopni.

**Comment by michalwarchol** [comment]
Proponuję skorzystanie z tego [głośniczka](https://eu.mouser.com/ProductDetail/CUI-Devices/CDS-4028-16?qs=Rp5uXu7WBW9mlyNssDdIqQ%3D%3D)

**Comment by michalwarchol** [comment]
Tutaj jest instrukcja jak coś takiego podpinać: https://os.mbed.com/users/4180_1/notebook/using-a-speaker-for-audio-output/

**Comment by michalwarchol** [comment]
Tutaj [model 3D](https://www.cuidevices.com/product/resource/3dmodel/cds-4028-16) tego głośnika

**Comment by michalwarchol** [comment]
> Przydatny może być też [ten poradnik](https://www.instructables.com/LETS-MAKE-a-PORTABLE-SPEAKER-ON-a-BREADBOARD/)

W tym poradniku jest też wykaz innych komponentów które są potrzebne do podłączania tego ustrojstwa. Jakieś kondensatory, potencjometr itp.

**Comment by michalwarchol** [comment]
Może sie jeszcze przydać taki [poradnik](https://youtu.be/qNLvoSQCx60)

**Comment by Tomasz-Zdeb** [comment]
> Proponuję skorzystanie z tego [głośniczka](https://eu.mouser.com/ProductDetail/CUI-Devices/CDS-4028-16?qs=Rp5uXu7WBW9mlyNssDdIqQ%3D%3D)

Mam problem z otwarciem zamieszczonego linku. Strona główna Mausera działa bez zarzutów, zatem musi to być problem z linkiem.

---

## Organizacja

### Nazwa i zakres Issue

Zalecam zmianę nazwy niniejszego **Issue** zgodnie z konwencją, na np.: "**Research i wybór komponentów do emisji sygnałów dźwiękowych po osiągnięciu konkretnych temperatur**" i oczywiście ograniczenie zakresu niniejszego **Issue** tylko do wyboru komponentów.

### Relizacja w odrębnym wątku (Issue)

Do samej realizacji zadania - tj. dodania komponentu do schematu i stworzenie treści, która będzie zawierać się w ostatecznym dokumencie stanowiącym nasz projekt, utwórzmy oddzielne **Issue** po zamknięciu tego, aby zachować jak największą granulację zadań, a co za tym idzie możliwość podziału obowiązków 😀

## Komentarz

Zasadniczo skorzystanie z takiego kolosa w naszym drobnym urządzeniu embedded, jest zdecydowanie overkillem, między innymi ze względu na rozmiary, konsumpcje energii elektrycznej, złożoność aplikacji a nawet cenę. 😯

## Komponenet

Tak na prawdę nie potrzebujemy emitować dźwięku złożonego z wielu tonów - **buzzer** wydaje się być idealnym rozwiązaniem. Zasadniczo nie zależy nam też szczególnie na modulacji tonu - więc dla uproszczenia możemy skorzystać z buzzera z generatorem 😎 co pozwoli na sterowanie po prostu za pomocą podawania sygnału wysokiego gdy chcemy emitować dźwięk i sygnału niskiego gdy nie chcemy emitować dźwięku. Oczywiście ton będzie z góry ustalony i nie będzie można go zmieniać, ale w takim urządzeniu zmiana tonu sygnału nie jest najważniejsza (tym bardziej w czasach kryzysu gospodarczego i braków na rynku półprzewodników 😪) 

Polecam: [komponent tego typu :)](https://botland.com.pl/buzzery-generatory-dzwieku/786-buzzer-z-generatorem-5v-12mm-tht-5904422366940.html?cd=18298825138&ad=&kd=&gclid=Cj0KCQiAgribBhDkARIsAASA5bskryWCcoTxmPSxg8C5Tb3lNpeTEYri21ly5YxOMWQMTysx1bbs-UMaAouBEALw_wcB). Wpasowuje się on w kontekst naszego urządzenia embedded zarówno pod względem rozmiaru, poboru energii, poziomu trudności aplikacji i ceny.

## Ustawianie thresholdu

Potencjometry stanowią efektywny sposób kontrolowania progu aktywacji. Ale z racji zastosowania interfejsu do komunikacji urządzenia z innymi urządzeniami, ciekawie byłoby móc modyfikować parametry naszego urządzenia również zdalnie.

Jeżeli próg będziemy modyfikować za pomocą potencjometrów, uniemożliwimy (albo skomplikujemy do stopnia pozbawiającego sens skorzystania z takiego rozwiązania) możliwość ustawiania parametrów zdalnie.

Proponuję skorzystać po prostu z **tact switchy** (które btw. również w pasowują się w kontekst naszego niewielkiego urządzenia embedded). Możemy skorzystać ze skojarzeń i zastosować color coding: [niebieski](https://botland.com.pl/tact-switch/11131-tact-switch-12x12mm-z-nasadka-kwadrat-niebieski-5szt-5904422307554.html) dla zmniejszania progu i [czerwony](https://botland.com.pl/tact-switch/11134-tact-switch-12x12mm-z-nasadka-kwadrat-czerwony-5szt-5904422307547.html) dla zwiększania progu.

Zmiana parametrów za pomocą impulsów (generowanych przez zwarcie przycisku) nie ogranicza nas w kontrolowaniu wartości parametru również zdalnie i przesuwa złożoność realizacji takiego rozwiązania w warstwę programistyczną a nie sprzętową. (czyli poza zakres naszego zadania)

## Konkluzja

Zastosowanie zaproponowanych przeze mnie rozwiązań uprości konstrukcje urządzenia i co również bardzo istotne dla nas jako realizatorów zadania uprości jego realizację 😉

**Comment by Tomasz-Zdeb** [comment]
W nawiązaniu do naszej rozmowy, uważam że zastosowanie zaproponowanego przez @michalwarchol [rozwiązania](https://arduinomodules.info/ky-006-passive-buzzer-module/?fbclid=IwAR2xrSQEQvXJQoSaBCyPUAT1Qpdzo6-RQKKRTS8gIRmnc9uBtt7pPz5gDqI) odpowiada potrzebom naszego urządzenia. Proponuję zastosowanie [tego modułu](https://botland.com.pl/buzzery-generatory-dzwieku/2963-modul-z-buzzerem-pasywnym-bez-generatora-czarny-5904422359263.html?cd=18298825651&ad=&kd=&gclid=CjwKCAiA76-dBhByEiwAA0_s9bgiyegkOrxPVHvjLPdCjIwSULFG82rgwxfOtnJEmOHJ_1PyzE-WoBoCAmwQAvD_BwE)
