### ISSUE TITLE
Stworzenie sekcji dotyczącej wyświetlacza LCD w main.md

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Embedded-Systems-Class-Project#15]
Element w postaci wyświetlacza LCD z konwerterem I2C został wybrany (#9). Następne kroki:

- [x] Stworzenie sekcji dotyczącej funkcjonalności realizowanej przez komponenty w pliku: [main.md](https://github.com/Tomasz-Zdeb/Embedded-Systems-Class-Project/blob/master/main.md). Treść powinna zawierać:
  - [x] Przedstawienie charakterystyki komponentów (wyświetlacz LCD i konwerter I2C) realizujących zadaną funkcjonalność
  - [x] Opis funkcjonalności
  - [x] Schemat logiczny obrazujący podłączenie komponentów (opcjonalnie)
- [x] Dodanie komponentów do schematu elektrycznego projektu. (katalog: [schematics](https://github.com/Tomasz-Zdeb/Embedded-Systems-Class-Project/tree/master/schematics))
  - [x] W przypadku braku odpowiedniego modelu stworzenie go
  - [x]  Połączenie modelu z układem (mikroprocesor i zasilanie)

**Comment by jackpie2** [comment]
Co do dodawania komponentów do schematu, to proponowałbym dodanie całej płytki konwertera, a nie samego układu PCF8574. PCF8574 jest dostępny w KiCadzie, ale podłączenie nie jest trywialne i z tego co rozumiem wymaga dodawania odpowiednich rezystorów i innych pośrednich elementów. 

Niestety nie znalazłem żadnej dokumentacji całego układu, na [stronie](https://botland.com.pl/wyswietlacze-alfanumeryczne-i-graficzne/2351-wyswietlacz-lcd-2x16-znakow-niebieski-konwerter-i2c-lcm1602-5904422309244.html) też nie ma linka do niej, a z mojego krótkiego researchu wynika też, że nazwa LCM1602 może dotyczyć samego wyświetlacza, choć i tutaj znalazłem sprzeczne informacje. W każdym razie [tutaj](https://www.mikrocontroller.net/attachment/521754/PCF8574_I2C_LCD_Cir_En.pdf) i [tutaj](https://www.electronicshub.org/pcf8574-i2c-lcd-with-arduino/) są jakieś sensowne opisy tych płytek i najlepiej byłoby na bazie tego stworzyć nowy, prosty komponent w KiCadzie, skupiając się głównie na wyjściach/wejściach, a następnie podpiąć go bezpośrednio do wyświetlacza LCD.

**Comment by Tomasz-Zdeb** [comment]
W związku z ostatnim [Pull Requestem](https://github.com/Tomasz-Zdeb/Embedded-Systems-Class-Project/pull/16) można odznaczyć podzadanie odpowiadające zaktualizowaniu schematu elektrycznego jako zrealizowane. Dobra robota! 👍

Teraz pozostały do zrobienia kolejne punkty, dotyczące opisu komponentu i funkcjonalności

**Comment by Tomasz-Zdeb** [comment]
## FYI
- w Issue: #28 zostały określone piny, używane przez konkretne interfejsy
- w Issue #25 dodano model mikroprocesora do schematu elektrycznego

W związku z czym można dodać komponenty do schematu elektrycznego wraz ze stworzeniem odpowiednich połączeń (co jest do zrobienia w ramach niniejszego zadania)
