### ISSUE TITLE
Stworzenie sekcji dotyczącej przechowywania danych w main.md

### ISSUE THREAD

**Issue by Tomasz-Zdeb** [Tomasz-Zdeb/Embedded-Systems-Class-Project#21]
Dokonano wyboru komponentów: (#10). Kolejne etapy realizacji projektu w kontekście niniejszej funkcjonalnośc to:
- [x] Stworzenie sekcji dotyczącej funkcjonalności realizowanej przez komponenty w pliku: [main.md](https://github.com/Tomasz-Zdeb/Embedded-Systems-Class-Project/blob/master/main.md). Treść powinna zawierać:
  - [x] Przedstawienie charakterystyki komponentów realizujących zadaną funkcjonalność
  - [x]  Opis funkcjonalności
  - [x] Schemat logiczny obrazujący podłączenie komponentów (Opcjonalnie)
- [x] Dodanie komponentów do schematu elektrycznego projektu (katalog: [schematics](https://github.com/Tomasz-Zdeb/Embedded-Systems-Class-Project/tree/master/schematics))
  - [x]  W przypadku braku odpowiedniego modelu stworzenie go
  - [x] Połączenie modelu z układem (mikroprocesor i zasilanie)

**Comment by Tomasz-Zdeb** [comment]
## FYI
- w Issue: #28 zostały określone piny, używane przez konkretne interfejsy
- w Issue #25 dodano model mikroprocesora do schematu elektrycznego

W związku z czym można dodać komponenty do schematu elektrycznego wraz ze stworzeniem odpowiednich połączeń (co jest do zrobienia w ramach niniejszego zadania)

**Comment by BlessedSamhain** [comment]
https://controllerstech.com/interface-sd-card-with-sdio-in-stm32/?fbclid=IwAR2p-ghQLy9oqxvOHQ20ZAalOFvRGLVjqF9gRw9ewYPpdKlW8OFwY_Fl_N8
