### ISSUE TITLE
Research i wstępny wybór mikroprocesora

### ISSUE THREAD

**Issue by Tomasz-Zdeb** [Tomasz-Zdeb/Embedded-Systems-Class-Project#22]
Aby móc tworzyć połączenia na schemacie elektrycznym niezbędne jest umieszczenie na nim mikroprocesora, dlatego model mikroprocesora musi zostać wybrany. Jeżeli po dodaniu wszystkich funkcjonalności będzie można zaobserwować redundancje możliwości (chodzi głównie o dostępne interfejsy) mikroprocesora, wówczas należy będzie skorygować wybór na model o mniejszej ilości interfejsów. Jeżeli nie wystąpi redundancja, wskazane będzie pozostanie przy wybranym mikroprocesorze
AC:
- [ ] dokonano wyboru mikroprocesora z modeli dostępnych w oprogramowaniu [STM32 IDE](https://www.st.com/en/development-tools/stm32cubeide.html)
- [ ] mikroprocesor obsługuje wszystkie (pod względem ilościowym i jakościowym) interfejsy używane przez komponenty urządzenia

**Comment by Tomasz-Zdeb** [comment]
### Wymagania
- **termopara**: SPI
- **wyświetlacz**: I2C, 2x wejście cyfrowe (BRIGHTNESS,CONTRAST)
- **pamięć**: SDIO
- **interfejs zewnętrzny** (Bluetooth) I2C/SPI - wybieram I2C
- **sygnały dźwiękowe** 3x wejście cyfrowe dla przycisku (UP,DOWN,TONE), wyjście PWM zdolne zapewnić prąd 30mA

**Comment by BlessedSamhain** [comment]
Proponuję zastosowanie mikroprocesora [STM32L151QDH6](https://www.mouser.pl/ProductDetail/STMicroelectronics/STM32L151QDH6?qs=pmcUWs1B1IIEPym5rr0MIA%3D%3D).
Obsługuje on wskazane powyżej interfejsy. Wyjątkowe wyzwanie stanowiło znalezienie mikroprocesora z rodziny STM32, który obsługuje **SDIO**, dostępnego na stanie magazynowym w sieci sklepów **Mouser Electronics**. Udało się to częściowo. Mikroprocesor jest dostępny na zamówienie, ale biorąc pod uwagę scenariusz powstawania naszego urządzenia powinno być to dopuszczalne.

Mikroprocesory z serii **STM32L151QDHx** są dostępne zarówno w programie **STM32CubeIDE**, jak i **KiCad**, w związku z czym będziemy mogli bezproblemowo zorientować się w potencjalnej konfiguracji (tzn. jaki interfejs możemy skonfigurować na jakim pinie), a następnie dodać go do schematu elektrycznego i dokonać odpowiednich połączeń (na podstawie wiedzy z etapu konfiguracji).

**Comment by Tomasz-Zdeb** [comment]
Super, zatem wybieramy rzeczony mikroprocesor. 👍
