### ISSUE TITLE
Określenie przykładowej konfiguracji mikroprocesora

### ISSUE THREAD

**Issue by Tomasz-Zdeb** [Tomasz-Zdeb/Embedded-Systems-Class-Project#28]
Zgodnie z Issues: #22 #25 wybraliśmy mikroprocesor i dodaliśmy go do schematu. Dalszym krokiem - bardzo istotnym, ponieważ blokuje on Issues: #11 #15 #21 #26 i #27 przed zrealizowaniem połączeń z mikroprocesorem na schemacie elektycznym jest określenie na których pinach mikroprocesora można skonfigurować daną funkcjonalność.

AC:
- Zgodnie z #22 sprawdzono potencjalną konfigurację używanych interfejsów (czyli np. na jakich pinach znajduje się SPI1 mikroprocesora itd...)
- Konfiguracja każdego z interfejsów jest umieszczona w niniejszym Issue w postaci screenshotów przedstawiających jakie piny są używane przez dany interfejs)

#### Przydatne Źródła
- [https://docs.espressif.com/projects/esp-at/en/latest/esp32/Compile_and_Develop/esp32-sdio-at-guide.html](https://docs.espressif.com/projects/esp-at/en/latest/esp32/Compile_and_Develop/esp32-sdio-at-guide.html)
- [https://www.digikey.pl/en/maker/projects/getting-started-with-stm32-how-to-use-spi/09eab3dfe74c4d0391aaaa99b0a8ee17](https://www.digikey.pl/en/maker/projects/getting-started-with-stm32-how-to-use-spi/09eab3dfe74c4d0391aaaa99b0a8ee17)
- [https://www.bluedot.space/tutorials/how-many-devices-can-you-connect-on-i2c-bus/](https://www.bluedot.space/tutorials/how-many-devices-can-you-connect-on-i2c-bus/)

#### Przykład z STM32CubeIDE dla SDIO
![2022-12-28_20h31_57](https://user-images.githubusercontent.com/62356875/209863411-a769811b-9690-4b72-968a-c74d25aaf193.png)

**Comment by KamilTworzydlo** [comment]
![Uploading D220C280-8694-4B93-9C6A-D2C037598093.png…]()

**Comment by KamilTworzydlo** [comment]
![67FB797B-7E90-4173-8DCE-E5C895227468](https://user-images.githubusercontent.com/45370284/210068474-96b17a58-e46b-418f-89b4-27e16ebf630b.png)

**Comment by KamilTworzydlo** [comment]
![Uploading 920447F1-CF58-4527-B8C5-0D5D335B50F2.png…]()

**Comment by KamilTworzydlo** [comment]
Wybrany mikroprocesor #22 obsługuje 4bitową obsługę **SDIO**, czyli natywną komunikację z nośnikami w postaci kart **SD** i **micro SD**. Prawdopodobnie tryb 1-bitowy zapewniłby wystarczającą prędkość transmisji do zapisu danych pozyskiwanych przez urządzenie, ale ze względu na jedynie częściowe wykorzystanie potencjału mikroprocesora, można skorzystać z trybu 4-bitowego zapewniającego bezpieczny zapas prędkości transmisji.
![00-sdio](https://user-images.githubusercontent.com/45370284/210102941-7f67a21b-6763-4b86-a689-d448a46944b6.png)
W przypadku konfiguracji interfejsu **I2C** można pozostawić domyślne ustawienia, ponieważ liczba urządzeń komunikujących się po tej magistrali będzie niewielka (2 komponenty i mikrokontroler), w związku z czym nie ma konieczności ingerencji w takie parametry jak prędkość zegara.
![01-I2C](https://user-images.githubusercontent.com/45370284/210103034-6c53cfd0-8e9d-4758-8ea9-b4ebd34a5216.png)
![02-I2C-config](https://user-images.githubusercontent.com/45370284/210103044-60a2a01f-03ee-4cca-9e47-4d6b4e7452e6.png)
Z analizy dokumentacji konwertera napięć termopary (modułu obsługującego termoparę #8):
https://www.mouser.pl/new/maxim-integrated/maximmax31855/ 
https://www.mouser.pl/pdfDocs/MAX31855.pdf
oraz analizie materiałów:
https://www.youtube.com/watch?v=eFKeNPJq50g&ab_channel=Digi-Key
https://fastbitlab.com/nss-setting-stm32-master-slave-mode/
https://www.digikey.com/en/maker/projects/getting-started-with-stm32-how-to-use-spi/09eab3dfe74c4d0391aaaa99b0a8ee17
konfiguracja interfejsu **SPI** sprowadzała się będzie do ustawienia trybu **Master** (Mikroprocesor-master, konwerter-slave) **half-duplex**.
![03-SPI](https://user-images.githubusercontent.com/45370284/210103072-c57c8c26-bb71-43f0-a579-38eb4a4cb48b.png)
![04-SPI-config](https://user-images.githubusercontent.com/45370284/210103082-6a94528e-fb3b-4c37-bf70-ff88d6834d0b.png)
Ze względu na brak jednolitego standardu komunikacji **SPI** istotne są parametry **CPOL** i **CPHA** określające przebieg transmisji względem polaryzaji zegara i linii danych. Według dokumentacji konwertera można pozostać przy ustawieniach domyślnych **STM32CubeIDE**, tj. polaryzacja zegara: sygnał niski (Low) i faza zegara na krawędzi narastającej (1 Edge). Są to najpopularniejsze wartości tych parametrów, jakie spotyka się w komunikacji **SPI**.
![05-SPI-additional-config](https://user-images.githubusercontent.com/45370284/210103110-88a1eab1-f8c9-42e6-accb-10e46c761134.png)
Najistotniejszym elementem konfiguracji wyjścia **PWM** jest ustawienie źródła sygnału zegara na zegar wewnętrzny i ustawienie generowania sygnału **PWM** na kanale pierwszym. Pozostałe parametry można pozostawić z wartościami domyślnymi.
![06-PWM-initial-config](https://user-images.githubusercontent.com/45370284/210103167-538d9363-2264-4527-b0a4-4ab654add1ef.png)
![07-PWM-lanes](https://user-images.githubusercontent.com/45370284/210103174-5c59f889-3b04-4981-9e7d-70fd8614bc07.png)
W przypadku wejść cyfrowych, konfiguracja polega na arbitralnym doborze nieużywanych pinów i ustawienia ich trybu pracy na **input mode**.
![08-GPIOs](https://user-images.githubusercontent.com/45370284/210103561-e883b06b-e6f9-4943-9bd7-8120d48f9738.png)

---

Z powyższej analizy konfiguracji uzyskujemy następujący pinout (**SYGNAŁ** -> **PIN**):

- SDIO
  - D0 -> PC8
  - D1 -> PC9
  - D2 -> PC10
  - D3 -> PC11
  - CK -> PC12
  - CMD -> PD2
- I2C
  - SCL -> PB8
  - SDA -> PB9
- SPI
  - MOSI -> PA12
  - NSS -> PA15
  - SCK -> PB3
- PWM
  - CH1 -> PA5
- GPIO
  - PB12
  - PB13
  - PD10
  - PD13
  - PE15

---

(Istotne dla osób podłączających komponenty na schemacie elektrycznym)

W przypadku konieczności zastosowania rezystora pull-up (pull up resistor) istnieje możliwość realizacji takiej funkcjonalności na etapie konfiguracji, nie trzeba wówczas fizycznie podłączać takowego rezystora.

https://en.wikipedia.org/wiki/Pull-up_resistor

**Comment by Tomasz-Zdeb** [comment]
Dobra robota 👍🏻 bardzo przystępne opracowanie 😀
