### ISSUE TITLE
Aktualizacja kosztorysu

### ISSUE THREAD

**Issue by Tomasz-Zdeb** [Tomasz-Zdeb/Embedded-Systems-Class-Project#33]
Aktualizacja kosztorysu stworzonego w ramach zadania: #29

AC:
- [x] kosztorys uwzględnia zaktualizowaną kartę **SD** i gniazdo - Issue #10
- [x] kosztorys uwzględnia trzy chipy interpretujące napięcia ale tylko jedną termoparę (zestaw podstawowy)
- [x] kosztorys uwzględnia trzy chipy interpretujące napięcia i cztery termopary (zestaw rozszerzony)
- [x] kosztorys uwzględnia mostek **I2C** to **SPI**
- [x] kosztorys w obu wariantach zawiera pięć zacisków <https://www.mouser.pl/ProductDetail/Amphenol-Anytek/VI0321550000G?qs=Mv7BduZupUjI2aG91xVokw%3D%3D> (cztery dla termopar i jeden na moduł rozszerzeń)
- [x] cena sumaryczna komponentów w kosztorysie nosi nazwę: `Cena prototypu`
- [x] kosztorys zawiera poniżej pola: `Cena prototypu` i `Cena seryjna` z wyjaśnieniem że przy zakupie komponentów w dużych ilościach cena jest mniejsza (zadecydować o wartości procentowej patrząc na ceny w zależności od ilości u dostawcy **Mouser Electronics**

**Comment by D4RK0N3dev** [comment]
3 czipy nie 4

**Comment by Tomasz-Zdeb** [comment]
Zaktualizowałem **Acceptance Criteria** o:
- trzy czipy
- trzy moski **I2C** to **SPI**
