### ISSUE TITLE
Research na temat software do projektowania schematów elektrycznych

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Embedded-Systems-Class-Project#4]
W projekcie potrzebny będzie schemat elektryczny urządzenia, a do jego wykonania przydałby się jakiś program. W związku z tym należy zrobić rozeznanie jakie oprogramowanie byłoby do tego najlepsze.

**Comment by Tomasz-Zdeb** [comment]
Priorytetem w poszukiwaniu softu do tego zadania powinna być prostota. Fajnie gdyby zawierał **out of the box** jakąś bazę komponentów w której znalazły by się mikrokontrolery z rodziny **STM32** aby można było zaimportować taki element.

**Comment by jackpie2** [comment]
Całkiem obiecująco wygląda [KiCad](https://www.kicad.org/), ma spory wybór komponentów z rodziny STM32, aktywną społeczność i też nie ma problemu z importowaniem do niego dodatkowych schematów.

**Comment by Tomasz-Zdeb** [comment]
Dobra robota 👍 Zatem ustalamy **KiCad** jako rekomendowany sofcik do stworzenia schematu elektrycznego
