### ISSUE TITLE
Research i wybór komponentu do pomiaru temperatury

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Embedded-Systems-Class-Project#8]
Zresearchowanie i wybranie komponentu do pomiaru temperatury z kategorii must have, wspomnianej w #1.

**Comment by jackpie2** [comment]
Jeśli chcemy dalej się trzymać termopary, to będzie potrzebny chip do interpretowania napięć. Na zajęciach został wspomniany przez prowadzącego [MAX31855](https://www.mouser.pl/new/maxim-integrated/maximmax31855/) i możemy przy tym zostać. Konkretny model wybierze się jak zostanie podjęta decyzja o typie termopary. Co do samej termopary, to szukamy raczej typów K i J, bo z mojego pobieżnego researchu wynika, że są najtańsze i najlepsze do powszechnych zastosowań. W każdym razie, moja propozycja termopary to:
https://www.mouser.pl/ProductDetail/Adafruit/270?qs=GURawfaeGuACMa%252Bo9T3i3g%3D%3D

Głównie dlatego, że w [dokumentacji ](https://www.mouser.pl/datasheet/2/737/thermocouple-932885.pdf) ma informacje o podpinaniu jej do wcześniej wspomnianego czipa i wydaje się to proste, no i też mamy pewność, że nie będzie problemów z połączeniem. Minusem jest cena (o ile chcemy minimalizować koszty), bo widziałem też termopary o połowę tańsze na innych stronach, np: [1](https://elty.pl/pl/p/Termopara-typu-K/850), [2](https://pl.rs-online.com/web/p/termopary/6212142).

**Comment by Tomasz-Zdeb** [comment]
Ciekawa propozycja. Dobra dokumentacja to bardzo ważny atut potencjalnego komponentu. Zachęcam do pozostania przy zaproponowanej parze komponentów.

---

Można zatem przejść do dalszego etapu realizacji zadania:

- [ ] Stworzenie sekcji dotyczącej funkcjonalności realizowanej przez komponenty w pliku: [main.md](https://github.com/Tomasz-Zdeb/Embedded-Systems-Class-Project/blob/master/main.md). Treść powinna zawierać:
   - [ ] Przedstawienie charakterystyki komponentów realizujących zadaną funkcjonalność
   - [ ] Schemat logiczny obrazujący podłączenie komponentów (ten z dokumentacji układu [MAX31855](https://www.mouser.pl/new/maxim-integrated/maximmax31855/) prezentuje się bardzo przejrzyście)
- [ ] Dodanie komponentów do schematu elektrycznego projektu (oczywiście ze względu na to, że nie dokonaliśmy jeszcze wyboru procesora nie będzie się dało dokonać wszystkich połączeń od razu.
