### ISSUE TITLE
Research i wybór wyświetlacza LCD

### ISSUE THREAD

**Issue by jackpie2** [Tomasz-Zdeb/Embedded-Systems-Class-Project#9]
Zresearchowanie i wybranie wyświetlacza LCD z kategorii must have, wspomnianej w #1.

**Comment by jackpie2** [comment]
Proponuje ten: [link](https://botland.com.pl/wyswietlacze-alfanumeryczne-i-graficzne/224-wyswietlacz-lcd-2x16-znakow-niebieski-5903351241380.html)

**Comment by Tomasz-Zdeb** [comment]
Super, myślę że wyświetlacz alfanumeryczny LCD 2x16 to super wybór! 😀

Myślę że w integracji z mikrokontrolerem, lepszy wybór stanowiłby tak wyświetlacz który zawiera od razu kontroler pozwalający na komunikację po jakiejś magistrali np. **I2C**. Podłączenie takiego komponentu byłoby nieporównywalnie łatwiejsze (4 linie vs 16 linii), a wysiłek związany z integracją zostałby wyekstrahowany do warstwy programistycznej.

Sugerowałbym: [komponent tego typu :)](https://botland.com.pl/wyswietlacze-alfanumeryczne-i-graficzne/2351-wyswietlacz-lcd-2x16-znakow-niebieski-konwerter-i2c-lcm1602-5904422309244.html)

Anyway, dobra robota! 😉

**Comment by jackpie2** [comment]
Z mojego researchu wynika, że raczej rzadko używa się 16 linii i na przykład do samego przesyłu informacji dotyczącej wyświetlanego tekstu używa się z reguły 4 z 8 dostępnych. Pomimo tego, podlinkowany komponent i tak wydaje się być prostszy w podłączeniu, więc rzeczywiście zastosowanie go jest lepszym pomysłem.

**Comment by Tomasz-Zdeb** [comment]
Trafna uwaga, nie byłem tego świadom 😀Oczywiście ostateczną decyzję pozostawiam Tobie @jackpie2.

Po podjęciu ostatecznej decyzji proszę o zamknięcie Issue (z jasnym zazczaczeniem który element został wybrany) i utworzenie Issue dotyczącego opisu funkcjonalności i komponentu w głównym dokumencie z zachowaniem konwencji nazewniczej, na przykładzie issue #11

**Comment by jackpie2** [comment]
Pozostańmy więc przy komponencie z konwerterem I2C.
